GET http://localhost:5678/notify/health

###

POST http://localhost:5678/notify/notification 

{
    "user_id": 1,
    "title": "Test Notification",
    "body": "This is a test notification.",
    "category": "chat",
    "payload": {"message_id": 12345}
}

###

GET http://localhost:5678/notify/notifications/1